sudo: required
cache: yarn
addons:
  chrome: stable
  sonarcloud:
    organization: agile-doms
    token:
      secure: "$SONAR_TOKEN"
language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install:
- npm install
- yarn install
script:
- ng build --prod --aot
- ng test
- yarn build
- sonar-scanner
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: EjZCJaqpPT7nlWwUPfErxKCtkbuEm8JwH6oM/UU33u36PAcwRvKCVz/+2Mla6IK5MM+rHehJKXFDFiRZ7YyBKnj8kSddtvil3ZShbQljTOcxSX2HF9d7E1Pg/zDWbIsszZ+gxj1wsmoaSHdIi5insRZNjTyIWO2Jvxcf3aD88SE6mFxLS6xMBcKNkUkgf+2qQm/kgQa0tkfMNIJ5/TZduVoq/XStUiHJ2m2JvxsTXdBXwacEHULB7uiKEoh25I4wv0DbGXXO9Ma4BXuJ0yUY+5vAUrBzXLS/W60Ug4o6ANilhqi90cZwJiQnY//NVqkhwZ4a7wmZGCpdU4ummEzZ6PCc5Y7vEnPdDimhY6lKn7LxjBfxx7tAPMh/EflDui7fIjXGepTec79UT0O3t+dOjqPsjxrsR+N9VBGc4ldQBEnn2m6VxLklBiYa+U39CFOv+PDlnGWclWX45itkjVJQIqDijdeFg9mZwmGWyCtfbyZjfIvgla+7WVSgbSHxQ1Ez1GyUHJhdwwCdq6WXa9sgp31ATeCvF5LvAfNU1Hg1DQ2nHdwPZDBMsyLZkoRaLfvT7KX+Oggf8k4UBT+NN6vTQs6oep56fgVdi1ADWjY5ctsD1yG3O6CLyyFIjxE2lZ7loq+D/UgVN/6f7209aNoUrWmjj5UCWGGAyzVz/rDrNIY=
  app: demodevops
  on:
    repo: agile-doms/demodevops
